import Foundation

/// Generates the contents of `~/.claude/lupen-statusline-tap.sh` — the
/// shell script Claude Code's `statusLine.command` points at after Lupen
/// is connected. The script delegates to the Lupen binary inside
/// Lupen.app when present, and gracefully degrades to running the user's
/// chained statusline directly when Lupen.app is missing (so a Lupen
/// uninstall doesn't take the user's existing statusline with it).
///
/// The template is generated from a single string with two
/// substitutions:
///   * `{LUPEN_BIN}`   — absolute path to the Lupen binary (e.g.
///                       `/Applications/Lupen.app/Contents/MacOS/Lupen`).
///   * `{TIMESTAMP}`  — ISO-8601 capture time, embedded in a comment
///                       for forensics.
enum WrapperScriptTemplate {

    /// Build the wrapper script body. Always invokes the binary with the
    /// `--statusline-tap` flag — which `main.swift` recognises before
    /// AppKit starts so the helper exits in a few hundred ms.
    static func render(lupenBinaryPath: String, timestamp: Date = Date()) -> String {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime]
        let stamp = formatter.string(from: timestamp)

        // The literal `--statusline-tap` is intentionally hard-coded
        // here rather than re-using `StatuslineTapMode.argvFlag` so a
        // grep for the flag finds both the producer (this template) and
        // the consumer (the argv handler) without dragging Swift into
        // the shell script's surface area.
        let escaped = shellEscape(lupenBinaryPath)
        return """
        #!/bin/bash
        # Lupen statusline tap wrapper
        # Generated by Lupen at \(stamp)
        #
        # Safe to delete if you're disconnecting Lupen. Restore the previous
        # statusline command in ~/.claude/settings.json afterwards.

        LUPEN_BIN=\(escaped)

        if [ -x "$LUPEN_BIN" ]; then
            exec "$LUPEN_BIN" --statusline-tap
        elif [ -n "$LUPEN_NEXT_STATUSLINE" ]; then
            # Lupen.app missing but a chain target is configured — keep the
            # user's existing statusline working.
            exec /bin/sh -c "$LUPEN_NEXT_STATUSLINE"
        else
            exit 0
        fi
        """
    }

    /// Best-effort shell-escape. The path comes from
    /// `Bundle.main.executablePath` so we don't expect adversarial input,
    /// but a path containing spaces or a literal `$` should still survive.
    /// Single-quote everything and double-up internal single quotes.
    static func shellEscape(_ value: String) -> String {
        let inner = value.replacingOccurrences(of: "'", with: "'\\''")
        return "'\(inner)'"
    }
}
